### ISSUE TITLE
Stored Mining Not Working for Gold Tools

### ISSUE THREAD

**Issue by bybandla** [shakhruz/angelfarmers-ui#31]
The bot is flawless, other than the gold membership stored mining,
I have silver gold memberships in place, but the bot is not considering them.

![Capture](https://user-images.githubusercontent.com/21012127/160234117-09928b71-ce5c-4543-8f93-562b9ef41dad.PNG)

**Comment by shakhruz** [comment]
thank you for reporting the issue! I will try to fix it after I see that there is or there is no game update this months. Only 4 days left to see the fate of this game. I hope you understand

**Comment by bybandla** [comment]
That's fine, the bot is already flawless and sleek. With the update, you might do some reprogramming so it's fine for now. :)
Thanks a lot again. ♥♥

**Comment by shakhruz** [comment]
Hi @bybandla ! I have updated with a small fix, please try it and let me know. I'm still crafting memberships in hope to get a gold one...

**Comment by bybandla** [comment]
Thanks a lot @shakhruz Glad you are active on this.
The gold membership store mining is not working yet.

My claim slot as per the stored mining:
![1](https://user-images.githubusercontent.com/21012127/161816591-e38ae533-4028-4ae6-a594-126c01a80535.PNG)

But the bot claiming at:
![2](https://user-images.githubusercontent.com/21012127/161816634-53f64378-4f77-48c8-aa54-0db000b00d0f.PNG)

**Comment by shakhruz** [comment]
I fixed another minor bug (typo) and it will hopefully work now. Please let me know. Thank you for helping!

**Comment by bybandla** [comment]
> I fixed another minor bug (typo) and it will hopefully work now. Please let me know. Thank you for helping!

Thanks a lot! Gold Membership Stored Mining is working now.
