### ISSUE TITLE
Transaction declares authority error

### ISSUE THREAD

**Issue by NFT-Gaming-Official** [shakhruz/angelfarmers-ui#32]
When using a non-wax cloud wallet, it seems to return this error. 

![Screenshot_2](https://user-images.githubusercontent.com/102363568/161422126-7eb0f0f4-6722-44c7-94ca-da68226be9a2.png)

**Comment by shakhruz** [comment]
did you fill in 'private key' field for the account with non-wax wallet? If you use private key, it has to be from 'farmer' permission, not 'active'. 

Did you use anchor wallet to login?

I just tested with anchor wallet, logged in and claimed a tool, everything worked. In the settings there should be no 'delegated' and 'private key' settings filled in.

**Comment by NFT-Gaming-Official** [comment]
All settled. Yea if it was logged in through anchor wallet, everything is fine. All is well! Great job on this! Looking forward to more features! 

Oh and one last thing, I think feeding the cow is bugged. I have 11 barley to feed the cow but it always returns an error of not enough barley to feed the cow.

**Comment by shakhruz** [comment]
yes, cows and chicken are hard. Bot is sending the transaction to feed them with barley ID, but somehow the smart contract is refusing to see that barley. Looks like a bug on their side. On the other hand it does work most of the sometimes, which means logic is fine. 

I'm still looking into this issue so help you for reporting!
