### ISSUE TITLE
Getting invalid base -58 value while transferring tokens to secondary account

### ISSUE THREAD

**Issue by R37RO** [shakhruz/angelfarmers-ui#34]
Getting "invalid base -58 value" left bottom red error popup, while transferring tokens to secondary account. 
my package.json  below, because some dependencies version throwing error upon yarn install so changed some version id
[package.json.txt](https://github.com/shakhruz/angelfarmers-ui/files/8502278/package.json.txt)
Thanks.

**Comment by R37RO** [comment]
![Image_1](https://user-images.githubusercontent.com/30890236/163757326-dff5ac0b-d166-41ce-929f-4ce6c1792508.png)

**Comment by R37RO** [comment]
![compare](https://user-images.githubusercontent.com/30890236/163817201-66acaa74-f734-478c-848d-a1bcfe7d685d.png)

**Comment by shakhruz** [comment]
Thank you for the contribution. I've found a bug in the code - there just should be another fiend before private key. Fix committed and deployed

**Comment by logneon** [comment]
Thanks 😀
